services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst_pass
      POSTGRES_DB: cyber_analyst
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
